### ISSUE TITLE
[SOLVED] Can't open the instance from Ubuntu Windows 10 Linux subsystem

### ISSUE THREAD

**Issue by luqaska** [toddsundsted/ktistec#10]
I followed all the steps given and it still doesn't work! :-(

**Comment by toddsundsted** [comment]
@luqaska where is it failing?

**Comment by luqaska** [comment]
> @luqaska where is it failing?

When I start the program, it doesn't make any log and it doesn't serve the 3000 port

**Comment by toddsundsted** [comment]
@luqaska how are you running the program, specifically? and what does the output look like? (can you provide a screenshot?)

**Comment by luqaska** [comment]
After 7-8 days of silence, I have officially resolved the problem....

Sorry for the late, I was doing stuff meanwhile.

This is so embarrassing....

The reason the "nothing log" problem was caused, was due to Crystal loading. I just had to wait more time until it decided to run...

I just (almost) finished the setting it up. I only have one last question to ask you: What is the "Canonical Path"?

**Comment by luqaska** [comment]
Oh... it bugged out....

**Comment by toddsundsted** [comment]
@luqaska great news!

you can compile the server and then run the resulting executable—that will save a lot of start up time.

```
crystal build src/ktistec/server.cr
LOG_LEVEL=INFO ./server
```

**Comment by toddsundsted** [comment]
> What I have to put on "Canonical Path"?

you don't need to put anything there. it's only useful if you want to publish a post at a specific URL. for example, post URLs are usually of the form "https://<hostname>/objects/<id>". if you set the canonical URL to something like "/foo/bar/baz" then the post would be at "https://<hostname>/foo/bar/baz".

**Comment by luqaska** [comment]
> you don't need to put anything there. it's only useful if you want to publish a post at a specific URL. for example, post URLs are usually of the form "https://<hostname>/objects/<id>". if you set the canonical URL to someth

Oh, that's cool

**Comment by luqaska** [comment]
> Oh... it bugged out....

I'll create a new issue for this

**Comment by luqaska** [comment]
> Oh... it bugged out....

Also... I'm using a reverse proxy... Do you know if it is possible that using this, the website could glitch out?

| ![Homepage localhost](https://midi.moe/f/ugfvb.PNG) | ![Homepage of the actual URL](https://midi.moe/f/gktub.PNG) |
| :-: | :-: |
| _(Homepage localhost)_ | _(Homepage of the actual URL)_ |

**Comment by luqaska** [comment]
Had a little error with the config of the website

> > Oh... it bugged out....
> 
> Also... I'm using a reverse proxy... Do you know if it is possible that using this, the website could glitch out?
> ![Homepage localhost](https://camo.githubusercontent.com/1d145d0135c57f541db6d4cded912e23b2be53b74b9499984cd695cb97ab31e8/68747470733a2f2f6d6964692e6d6f652f662f75676676622e504e47) 	![Homepage of the actual URL](https://camo.githubusercontent.com/f0f77274e2288752c73e1a20117a73f8dc0edc94673bc59e06b0998f156699f1/68747470733a2f2f6d6964692e6d6f652f662f676b7475622e504e47)
> _(Homepage localhost)_ 	_(Homepage of the actual URL)_

Ok, it apparently fixed itself! Thank you @toddsundsted for your help through this issue!
