### ISSUE TITLE
When I accidently press [Publish Post] twice, it results in two identical posts

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#101]
If I press [Publish Post] twice accidentally, (and it seems to happen to me often) it results in two identical posts. Ideally, multiple presses of the [Publish Post] on the same page should result only on one post.

**Comment by toddsundsted** [comment]
i've confirmed this bug myself. this is typically handled but the hotwired framework for form submission, but the editor has its own functionality for this, which doesn't disable the button. should be easy to fix.

thanks for highlighting this bug!

**Comment by toddsundsted** [comment]
should be fixed in e158edf0
