### ISSUE TITLE
Http requests signed with the `hs2019` algorithm and without `(create)` http header should be acceptable

### ISSUE THREAD

**Issue by LindsayZhou** [toddsundsted/ktistec#103]
Version: 2.0.0-11
Install from: Alpine Linux package manager (`apk`)

The [spec](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12#section-2.1.4) mentions `(create)` http headers as recommended, ktistec implements it as required: 

https://github.com/toddsundsted/ktistec/blob/648b46397883f79a70b705c20fd3526186662bd0/src/framework/signature.cr#L80-L82

Other instances that have not implemented the `(create)` http header can not interact with ktistec instances.

Gotosocial issue: https://github.com/superseriousbusiness/gotosocial/issues/2857

**Comment by toddsundsted** [comment]
@LindsayZhou i changed this logic to follow the kind of validation that Mastodon does.

before i merge the change, i'd like to test it. i currently have it running at https://epiktistes.com/. do you have access to a gotosocial account and can you send a follow request from that account?

**Comment by toddsundsted** [comment]
i pushed the changes in dd07bcae

**Comment by toddsundsted** [comment]
follow received and `accept` sent.

thank you!
