### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Cellesti** [toddsundsted/ktistec#106]
Hi, i am the maintainer of the Ktistec package in Alpine Linux. It was recently brought to my attention that the Alpine package has misinterpreted the versioning scheme you use.

As the `-` character is not allowed in versions for Alpine packages, we turned it into a `.`, so `2.0.0-11` became `2.0.0.11`.

With the release of `2.0.0`, we have realized our mistake, that you intended `2.0.0-11` to be a pre-`2.0.0` release.

However that is a bit too late, Alpine's package manager considers `2.0.0.11` a post-`2.0.0` version, so if we add `2.0.0` into the repository, the package manager will not automatically upgrade to it.

We will learn from this, and in the future, if you tag `3.0.0-1` we will translate it into a version the package manager recognizes as a pre-`3.0.0` version.

For now, i am writing to you to ask about the possibility of having a `2.0.1` release, so over at Alpine, we will be able to provide a straightforward upgrade path for our users.

Considering that you've just tagged `2.0.0`, i understand you may have reservations about tagging another version so soon afterwards, but i hope you will give this request some consideration.

Thanks.

**Comment by toddsundsted** [comment]
> For now, i am writing to you to ask about the possibility of having a 2.0.1 release, so over at Alpine, we will be able to provide a straightforward upgrade path for our users.

of course. i just tagged v2.1.0 which includes upgrades for application dependencies. i hope this helps resolve this for you!

**Comment by toddsundsted** [comment]
and then i screwed up my own tagging scheme and tagged commits on the `main` branch instead of the `dist` branch. can you hold off on making a new release until i fix that.

**Comment by toddsundsted** [comment]
ok, git tags fixed.

**Comment by toddsundsted** [comment]
what triggers a new release? is the tagging a commit in git or is it updating the version in shards.yml? are you packaging `main` or `dist`?

**Comment by toddsundsted** [comment]
@Cellesti thanks!

i will be making a new release in a short time. i will endeavor to get all of the steps correct on my end so that no patches are necessary.

**Comment by toddsundsted** [comment]
@Cellesti i have just released 2.2.0

let me know if you run into problems packaging this
