### ISSUE TITLE
How to customize the CSS of ktistec

### ISSUE THREAD

**Issue by wychwitch** [toddsundsted/ktistec#12]
Hello!! Please forgive me I'm VERY new to Crystal and less, however I still tried poking around a bit but I haven't been able to figure out how to customize the css my ktistec.

I added my custom styles to the bottom of the `src/assets/main.less` file and ran `LOG_LEVEL=INFO crystal run src/ktistec/server.cr` and it seems to completely ignore my changes (I force refreshed as well)

How should I go about this? Many thanks in advance!!

**Comment by toddsundsted** [comment]
@wychwitch you need to install nodejs (i use 14.16.x) and rebuild the assets.
```
npm run build --production
```
this will rebuild the assets in src/assets and install them in public/dist. then, when you run the server, it should serve the latest assets.

i need to update the readme.

**Comment by wychwitch** [comment]
> @wychwitch you need to install nodejs (i use 14.16.x) and rebuild the assets.
> ```
> npm run build --production
> ```
> this will rebuild the assets in src/assets and install them in public/dist. then, when you run the server, it should serve the latest assets.
> 
> i need to update the readme.

Ah thank you!!  This is exactly what I needed! I'll also use the same node (thank God for nvm)
