### ISSUE TITLE
Can I read posts from other instances with ktistec?

### ISSUE THREAD

**Issue by tripod3d** [toddsundsted/ktistec#15]
Hi, thanks for this software.

I am trying to get a software to publish and read from the fediverse, but seems that ktistec is only for writing a publishing content, not for read.

Am I wrong? Can I read people from the fediverse on my instance of ktistec?

Thanks a lot-

**Comment by toddsundsted** [comment]
@tripod3d you can if another activitypub instance sends content addressed to you to your instance. a common way to accomplish that is to _follow_ another fediverse user. on a new ktistec instance you can find other users by going to the Search screen (/search) and searching for a user by their handle (e.g. toddsundsted@epiktistes.com). there should be a Follow button on the results page.

there's no way to read content from arbitrary other users off of their instances without following, however.

**Comment by tripod3d** [comment]
> there's no way to read content from arbitrary other users off of their instances without following, however.

thank you. That's what I wanted to know. So there is no a way to see what is happening around the fediverse, right? I really liked the simplicity of this software. Do you know any software like this but with fediverse discovery? Thank you.

**Comment by toddsundsted** [comment]
there is not in the sense that you might get if you were using mastodon, for example.
