### ISSUE TITLE
On publishing a post, I get errors

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#19]
I am using the bundled docker file. I get the following error
```
Exception: Error opening file with mode 'r': '/app/etc/rules/content.rules': No such file or directory (File::NotFoundError)
  from ???
  from ???
  from ???
```
When I click [publish]

**Comment by toddsundsted** [comment]
i need to copy the etc/rules directory into the docker image. the rules used to be embedded, but i want the flexibility to modify them without recompiling.

**Comment by toddsundsted** [comment]
@vrthra i added the missing rules to the Dockerfiile. posting (and receiving) should work correctly now. thank you for submitting this! confirm and i'll close the issue.

**Comment by vrthra** [comment]
Yes, thank you, it is working now.
