### ISSUE TITLE
Changes to the site does not persist.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#22]
I am using the docker script to run ktistec. If I stop and restart the server, the server starts back on a blank slate including asking for the initial user.

**Comment by EvanKrall** [comment]
You'll need to ensure you mount a [volume](https://docs.docker.com/storage/volumes/) or [bind-mount](https://docs.docker.com/storage/bind-mounts/) at `/db` and `/uploads`

**Comment by vrthra** [comment]
How do I use these? Any guidelines?

**Comment by toddsundsted** [comment]
@vrthra i do something like the following:
```
mkdir ktistec
cd ktistec
mkdir db uploads
cp <from wherever you checked out the project> .
docker build -t "ktistec:latest" .
docker run -p 3000:3000 -v `pwd`/db:/db -v `pwd`/uploads:/uploads ktistec:latest
```

the links above give more information on how those work with docker.

**Comment by toddsundsted** [comment]
the database and updates should persist to the two directories between runs.
