### ISSUE TITLE
Failure to run (docker)

### ISSUE THREAD

**Issue by winks** [toddsundsted/ktistec#27]
I've been trying to play around with the latest version but I'm constantly getting this:

```
$ docker run --rm -it ktistec-dev:latest /bin/sh
sh-4.4# /bin/server
create-accounts: applied in 0.0288s
create-sessions: applied in 0.0315s
create-actors: applied in 0.0392s
create-relationships: applied in 0.0434s
create-collections: applied in 0.0284s
create-objects: applied in 0.0515s
create-activities: applied in 0.0364s
create-tasks: applied in 0.0364s
create-tags: applied in 0.0402s
create-tag-statistics: applied in 0.0122s
update-timeline-and-notifications: applied in 0.0005s
create-points: applied in 0.0258s
add-timezone: applied in 0.0085s
add-state: applied in 0.0097s
add-blocked-at-to-actors: applied in 0.0097s
add-blocked-at-to-objects: applied in 0.0117s
add-name-to-objects: applied in 0.0096s
add-undone-at-to-activities: applied in 0.0098s
add-index-on-attributed-to-iri-to-activities: applied in 0.0135s
Unhandled exception: Error opening file with mode 'r': '/app/etc/rules/content.rules': No such file or directory (File::NotFoundError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

I thought it might be some alpine oddity, but also changing the 2nd part of the multistage build to run on ubi8 didn't help. (`FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6-941`)

Bit of a loss here at it seems to run fine for others and so far I couldn't dig up anything helpful. This was built on Arch as the server I'm usually hosting on doesn't have enough RAM, but even after saving and importing the image it doesn't work, as expected.

**Comment by toddsundsted** [comment]
@winks that should have been fixed in https://github.com/toddsundsted/ktistec/commit/e6abe307c971749f6cf3287e19cd79f953986f32.

when did you build the ktistec-dev:latest image you are using? can you paste the output from that build here so i can see the build steps. thanks!

**Comment by winks** [comment]
Argh, now I feel like an idiot, it works - thanks! (had to run shards update though)

I guess the reason it went wrong (not your fault ofc) is that I've been playing around on and off for a week and I guess I missed the Dockerfile update 3d ago. As the `dist` branch is checked out in the build/container, of course that doesn't help if I downloaded the Dockerfile before that... so I was missing that line 

Just out of curiosity, watching this repo - I seem to not understand at all what master/dist are really doing and how there are so many more commits in dist and yet that's the one you're only merging to from time to time...

**Comment by adyxax** [comment]
It seems the dist branch gets additional commits after merging, look for the commits titled "Update assets for distribution" which contains the result of `npm run build`.

**Comment by toddsundsted** [comment]
yes, the point was to save everyone the step of having to install the javascript webpack-based build chain.

two questions:
1) is this actually useful? maybe having main AND dist is more confusing than useful.
2) is the Dockerfile useful? i don't personally use the Dockerfile, so i often forget to test it, which results in some recent problems for users.

**Comment by winks** [comment]
I've been meaning to look into the code since... about April but I've not found the time, so I'm just running it as a user, for now and not working on a few tiny things I'd probably be running off a branch or contributing :)

The Dockerfile is very helpful, but I'd have no problem going off a README or just a release. Don't want to cause you any extra work, so whatever works.

**Comment by felixkrohn** [comment]
Yes, the Dockerfile is really useful.
Maybe the confusion about the branches could be fixed by renaming them? For example: main -> dev; dist -> main

**Comment by toddsundsted** [comment]
thanks all!
