### ISSUE TITLE
Issue at https://epiktistes.com/@toddsundsted

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#28]
If I open https://epiktistes.com/@toddsundsted and click on follow, it asks me the address of my unique identity in fediverse. I enter `@rahul@gopinath.org` because I have a Ktistec server running at `gopinath.org`. I then get the following error

![error](https://user-images.githubusercontent.com/70410/201274399-95236808-4775-4428-8cd9-4b755621fd9b.jpg)

**Comment by felixkrohn** [comment]
I can confirm this behaviour and am available for further tests as well, if needed.

**Comment by toddsundsted** [comment]
@vrthra @felixkrohn thanks for reporting. it should be fixed. it wasn't a ktistec issue per se—i'd started my server instance without pointing it at the correct set of root certificates on my host, and all ssl requests were failing.

**Comment by toddsundsted** [comment]
if you can try again and confirm it now works, i will close this issue.

**Comment by felixkrohn** [comment]
@toddsundsted Yep, I can confirm.

**Comment by vrthra** [comment]
Confirming that it works now.
