### ISSUE TITLE
How do I repond to an older post?

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#30]
Hello, in https://epiktistes.com/@toddsundsted, I want to respond to [a post](https://epiktistes.com/objects/HNk1by2Lhz0) that was made before I started following you. However, I see no option to respond in the page at epiktistes, nor can I see that post in my own server (because the server is new, and it does not fetch older posts). How do I respond to this post?

![kt](https://user-images.githubusercontent.com/70410/201429232-75c2f803-4671-428b-92a9-ac0bf3bc0a28.jpg)

**Comment by toddsundsted** [comment]
@vrthra you can Search for a post by its URL, which will fetch that post into your database. from there you can reply to it, like it, etc. etc. it's klunky for sure. probably time to add remote reply (or whatever it's called).

**Comment by vrthra** [comment]
Thanks! Much appreciated.
