### ISSUE TITLE
Customizing the front page

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#33]
For example, since this is a single user site, I would really like to remove the heading _Community_ from the front page, also Sign In, and add a few more menu links to the top. How do I do that?

**Comment by toddsundsted** [comment]
@vrthra the view templates are all in src/views. in this case src/views/home/index.html.slang.

the views are compiled into the server, however, so you'll have to build a server—they aren't dynamically reloaded. that said, once i fix the problem with notifications, i'll probably remove them myself.

the header is in src/views/partials/header.html.slang

**Comment by vrthra** [comment]
Thanks! I will check these out.

**Comment by toddsundsted** [comment]
@vrthra i'm going to close this. i've made a change to remove the headings. other changes will need to be made to a fork of ktistec, for the time being.

in other issues there are suggestions to make more aspects of the site configurable. i'd support showing/hiding things like the Sign In link if that were implemented.
