### ISSUE TITLE
OpenSSL::SSL::Error while talking to the fediverse

### ISSUE THREAD

**Issue by knobhead** [toddsundsted/ktistec#4]
Sooo, I took a giant leap today in getting to grips with ktistec.

Here's what I managed to achieve today.

* [x] set-up a Virtualbox with most recent Alpine Linux x86_64
* [x] uncommented community repository in `/etc/apk/repositories`
* [x] `apk update`
* [x] `apk add git crystal shards`
* [x] `apk add`'ed various libraries and dev headers:
    * `apk add --virtual build-dependencies build-base gcc`
    * `apk add openssl openssl-dev openssl-static-libs` (messed that up before with `openssl3` package from `edge` repo)
    * `apk add libxml2` and probably some more, lost track somewhere ...
    * `apk add zlib` same as above
    * `apk add libsqlite3` same as above
    * `apk add libevent` same as above
* [x] `git clone -b dist https://github.com/toddsundsted/ktistec`
* [x] `cd ktistec`
* [x] `shards install`
* [x] `crystal build -p --release --static src/ktistec/server.cr`
🥳 **Yaay, I have a running, portable build!**
* [x] moved the binary to my webhost

On my webhost (uberspace running CentOS and Apache)

* [x] installed it as a service (via `supervisord`) behind a correctly configured reverse proxy
* [x] `git clone -b dist https://github.com/toddsundsted/ktistec` (into the `DocumentRoot` of this server for now)
* [x] `npm install`
* [x] `npm run build`
* [x] run `server` and stare at its `stdout`
* 🥳 **Yaay, it works!** I can access my installation with the browser, upload background and profile picture and post stuff! 😍

What doesn't work:

❌ I can't search for users on other fediverse instances. Front-end gives me this error:  
   `SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`
❌ I can't follow my ktistec user from my mastodon account. Search on my mastodon host does find it, but follow request (or in this example, cancelling a follow request) gives this stacktrace in `server` output:

```
2022-01-23T18:03:19.362446Z   INFO - {"@context" => "https://www.w3.org/ns/activitystreams", "id" => "https://mymastodoninstance.net/users/knobhead#follows/468655/undo", "type" => "Undo", "actor" => "https://mymastodoninstance.net/users/knobhead", "object" => {"id" => "https://mymastodoninstance.net/8a7c807d-c78f-4147-acfc-0a9581773bf9", "type" => "Follow", "actor" => "https://mymastodoninstance.net/users/knobhead", "object" => "https://tinyblog.knobhead.de/actors/knobhead"}}
Exception: SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (OpenSSL::SSL::Error)
  from /usr/lib/crystal/core/time/span.cr:75:15 in 'io'
  from /usr/lib/crystal/core/http/client.cr:671:19 in 'send_request'
  from /usr/lib/crystal/core/http/client.cr:603:18 in 'exec_internal_single'
  from /usr/lib/crystal/core/http/client.cr:587:18 in 'exec'
  from /usr/lib/crystal/core/http/client.cr:713:5 in 'get'
  from /root/ktistec/src/framework/open.cr:11:14 in 'open'
  from /root/ktistec/src/controllers/inboxes.cr:46:52 in '->'
  from /root/ktistec/lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /root/ktistec/lib/kemal/src/kemal/static_file_handler.cr:11:11 in 'call'
  from /root/ktistec/lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /root/ktistec/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from ???

2022-01-23 18:03:19 UTC 500 POST /actors/knobhead/inbox 467.33ms
```

Most likely I missed some simple configuration thing or didn't set the correct path to the certificate store or so?

I'd be grateful for any hint!

(And I might contribute to an installation how-to or something! man, this was tricky for me! :sweat_smile: )

**Comment by knobhead** [comment]
(Just noticed that the paths given in the exception do not match the paths of the webserver, those seem to refer to the alpine linux system. Is that relevant?)

**Comment by toddsundsted** [comment]
when i ran the static build on my server (centos, as well) i had to tell it where to find the certificates:

  https://epiktistes.com/objects/ZQYmg40cm9w

if you can run in a container, you can also try out my dockerized build:

  https://hub.docker.com/r/toddsundsted/ktistec

**Comment by toddsundsted** [comment]
from the linked post:
```
SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt ./server
```

**Comment by knobhead** [comment]
Thanks a lot, this solved it!
