### ISSUE TITLE
Random notifications being produced

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#40]
I am getting notifications like these. 

![Untitled](https://user-images.githubusercontent.com/70410/201642642-b7239176-704f-4c23-9f04-e6a591e9090d.jpg)

But none of them have me tagged. For example, one of them is

![Untitled](https://user-images.githubusercontent.com/70410/201642952-bca6101b-84a8-46b7-a143-af019e5ce497.jpg)

**Comment by JayVii** [comment]
Duplicate of #21

**Comment by vrthra** [comment]
You are right; I will close this.
