### ISSUE TITLE
Turning off images on a post

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#46]
I am running Ktistec on a fairly low power machine with limited bandwidth. If possible, I want to turn off images and other media in posts that I see so that I can conserve my bandwidth (possibly with a link to expand the image or the post if necessary). Is there any way I can do this?

**Comment by toddsundsted** [comment]
@vrthra ktistec does not store images on the server (other than images you upload with your own posts). the images and other media that you see in posts are downloaded by the client/the browser from the origin.

**Comment by vrthra** [comment]
Ah, I see, much appreciated.
