### ISSUE TITLE
Images are cropped rather than resized.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#53]
In many cases, the images are shown cropped rather than resized. Compare

![mem](https://user-images.githubusercontent.com/70410/204668780-26924248-df86-4d68-a571-e40b8a8ac8c0.jpg)

and how it is shown with Ktistec

![mem](https://user-images.githubusercontent.com/70410/204668917-ab595a95-a48c-4d1b-97df-f1d68031f9f3.jpg)

The image should be resized to fit rather than cropped.

**Comment by toddsundsted** [comment]
i used "object-fit: cover" to style images—"cover" both resizes and clips the image. mastodon uses this, as well—however, mastodon switches up the space given to images between listing and single posts, which is probably more useful. i'm open to the idea. it's probably just s small bit of css.

**Comment by toddsundsted** [comment]
@vrthra the most recent release of code should fix this. what i try to do is more closely mimic the presentation of attachments in mastodon. the specific post above, for example, should look quite a bit better now.

**Comment by vrthra** [comment]
Thank you, much appreciated!
