### ISSUE TITLE
third-party dependencies at runtime (jquery.com/cloudflare.com)

### ISSUE THREAD

**Issue by felixkrohn** [toddsundsted/ktistec#56]
I noticed that at least three external dependencies are pulled in from third-party sources at runtime:

1. https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js
2. https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css
3. https://code.jquery.com/jquery-3.4.1.min.js

without which elemntar functions of ktistec dont work (like viewing image attachments)
I personally strongly dislike that, because it's against my goals of self-hosting: being independent from third parties and not force users/visitors to pull in 3rd-party stuff and potentially make themselves vulnerable/observable.

From what I understand about web stuff (which isn't much) and licensing (same) these could be pulled at build time from their upstream equivalents, and included in the docker image:

1. https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.min.js
2. https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.min.css
3. https://releases.jquery.com/git/jquery-3.x-git.min.js

All of the above seem to be under MIT license, which seems to allow redistribution.

Or is there any legal or technical reason against this?

**Comment by toddsundsted** [comment]
no, i agree, and i have a branch open locally where i am addressing this incrementally. the first step is replacing semantic ui with fomantic ui (the maintained branch of this dependency) and fixing visual defects in the upgrade; then removing semantic.min.js which is only required to three small effects, all of which can easily be coded by hand; and finally making that part of the local build. the second step is removing jquery entirely. taken together, this will address these.

i'm down to one final visual defect. so i'm close, but i haven't been able to fix it so i'm still struggling with that.

**Comment by toddsundsted** [comment]
all dependencies on externally hosted assets should be gone: https://github.com/toddsundsted/ktistec/commit/2d643fe7

**Comment by felixkrohn** [comment]
Great news, thanks @toddsundsted !
