### ISSUE TITLE
Installer "Error: while requiring "..controllers/**"

### ISSUE THREAD

**Issue by VenielOuria** [toddsundsted/ktistec#62]
Greetings,
I'm following the install instructions, got all the prerequisites, up to the 
 > crystal build /src/ktistec/server.cr

after about 10 sec it throws an error
 > "Error: while requiring "..controllers/**"

No other info. Is this a common issue. Or is there a way to have more verbose output so I can track down the cause? No previous experience with Crystal.

**Comment by toddsundsted** [comment]
what directory are you in when you issued the build command? you'd have to be in the root directory (/) and the project checked out there for that command to work. did you type "crystal build src/ktistec/server.cr" instead (that's what i would have expected).

**Comment by toddsundsted** [comment]
it should be run from the project root. can you show me the steps you are taking, starting from a fresh clone of the repository. it would also help to know more about the system you are running and the version of crystal you have installed.

**Comment by toddsundsted** [comment]
what is the contents, ownership and permissions of the files in src/controllers?

**Comment by toddsundsted** [comment]
@VenielOuria following up... your project directory seems fine. i don't have any other suggestions for troubleshooting, or theories as to what could be going wrong in your build.
