### ISSUE TITLE
Request for a `Federated` stream.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#63]
I love `Ktistec` and it is my primary instance. However, I find myself going back to mastodon instances to find people to follow from interesting posts. It would be really great if Ktistec can give me some way to display a federated stream of posts from specified mastodon instances. (Is this something within the scope of ActivityPub, or is it Mastodon specific?)

**Comment by toddsundsted** [comment]
generally tackling discovery of users and content is something i'm interested in—i have the same problem.

ktistec _does_ have a "federated" stream—it's not documented but it's at /everything and it shows everything that server instance has received. however, with only one user, there's not much surface area. i've had an instance (mastodon and then ktistec) running at the same URL for several years, so my feed is pretty busy, but i suspect it's not for a new instance.

**Comment by toddsundsted** [comment]
@vrthra the homepage timeline implements a handful of rules to ensure that everything it shows is actually intended for you (for example, was the post actually addressed to you, was the post from someone who you are following, etc. etc.). nothing prevents someone from just delivering a post, or other activity, to your inbox, and approximately half of what hits my inbox is from people i don't even recognize. /everything, though, shows it all. i use it for debugging, etc. etc.

**Comment by vrthra** [comment]
Thank you! That sounds like it should help.

**Comment by toddsundsted** [comment]
@vrthra 5ad2f25e creates an navigable link to the `/everything` page and improves the underlying query enough to make the page legitimately useful.
