### ISSUE TITLE
Boosted replies are broken out of context

### ISSUE THREAD

**Issue by winks** [toddsundsted/ktistec#64]
OK, this might be a bit hard to describe, but the gist is that I had this post in my timeline: https://ruby.social/@alexanderadam/109688269873868125 via a boost by "relistan @ mstdn.social", who I follow on my ktistec account.

It looks like this in the timeline:
![sup_reply1](https://user-images.githubusercontent.com/44402/212533703-c4c738ff-6cbe-4a2b-98be-679a8729a62e.png)

and like this in the /remote/objects/xxx view:
![sup_reply2](https://user-images.githubusercontent.com/44402/212533712-ffa63e48-ac1f-4b82-9b18-b10081697608.png)

As you can see on the original post, it's a reply - and I have no other means to get to see the thread than (currently) clicking on the 4:29pm link on the timeline, then I get to the second picture, then I need to click on the poster's name, then I get to /remote/actors/zzz, then I click on their fedi handle "xx @ example.org", then I land on their real timeline, then I need to find the actual post and see who they replied to.

Maybe I am missing something, and part of it would already be solved by being able to directly get to the canonical url (I think vrthra posted a diff in some other issue, but I can't find it right now and it's not merged), but my main point is that I think on /remote/objects/xxx something could be improved, just not sure what, probably not grabbing the entire thread, but maybe (if we have that info) some sort of "..." [actual post]" "..." to show that it has ancestors and followups.

**Comment by toddsundsted** [comment]
there are a few things here: i had the same problem, and ended up "adding" it to my system by finding the URL of the original post and then searching for it on my instance by the URL, which added it to my system and made the full thread visible. what ktistec _should_ do is just automatically fetch replied to posts that it doesn't already know about—i'll probably do something like that in the near future (though it might be manual and not automatic).

in the short term, i'm totally supportive of adding a link to the original post on the origin server. the patch was for actors—it's mostly just a matter of deciding where to put the link.

**Comment by toddsundsted** [comment]
commit https://github.com/toddsundsted/ktistec/commit/4a90a542dfdc59e1a4842cdd9e16d7bef57fac61 adds support for two things: 1) a link to the original source post on the origin server, 2) a "Fetch" button that will pull the post over to the local server so that it's visible in the thread alongside (or above) the other posts. @winks i think this should come close to fixing this.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/58405/216725015-74c32057-d78f-45f0-8b58-e74362e54455.png">
