### ISSUE TITLE
Fails to build with Crystal 1.7.0

### ISSUE THREAD

**Issue by mohd-akram** [toddsundsted/ktistec#65]
I get this error when building:

```
Error target ktistec failed to compile:
In src/rules/content_rules.cr:23:33

 23 | class ::ActivityPub::Activity include School::DomainType end
                                    ^
Error: unexpected token: "include"
```

**Comment by toddsundsted** [comment]
@mohd-akram what version of crystal are you using?

**Comment by toddsundsted** [comment]
interesting, it fails for me with 1.7.1

**Comment by toddsundsted** [comment]
it's easy enough to fix. but let me check first and see if this change was intentional or a regression.

**Comment by toddsundsted** [comment]
thanks for reporting. created https://github.com/crystal-lang/crystal/issues/12974

**Comment by mohd-akram** [comment]
Thanks for following up on this. Crystal 1.7.2 has been released with a fix and ktistec successfully builds now.
