### ISSUE TITLE
Minimum RAM requirements?

### ISSUE THREAD

**Issue by N1ck75** [toddsundsted/ktistec#68]
I'm getting OOM killer on build 

"Out of memory: Killed process 860 (crystal) total-vm:3880680kB"

My VPS is running 4GB

**Comment by toddsundsted** [comment]
i'm late to this issue, but fwiw i just [committed code](https://github.com/toddsundsted/ktistec/commit/9acf0c3da86386c28d30d2a726052eafb9013804) that knocks the compile time and process size down quite a bit for me. i'll be doing more optimization over the next couples weeks, but i'd be happy to know if this works for you now.

**Comment by sdogruyol** [comment]
Curious to see the result of @toddsundsted's changes. Are you doing a release build @N1ck75? 

@toddsundsted I'm also thinking of checking block vs proc thing for Kemal itself 👍 Thanks a lot for using Kemal 🙏

**Comment by toddsundsted** [comment]
> I'm also thinking of checking block vs proc thing for Kemal itself 👍 Thanks a lot for using Kemal 🙏

a warning of some kind, once the inlined code is over some size threshold, would be ideal imo!
