### ISSUE TITLE
Following kbin magazines does not work.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#72]
I tried following @science@kbin.social, but getting this error.

![image](https://github.com/toddsundsted/ktistec/assets/70410/41ea9b2f-293d-4efe-9e96-1c1c33b8fffc)

Edit: This is working for me now. Not sure what changed.
meta-edit: [This](https://www.reddit.com/r/Mastodon/comments/146jxnf/unable_to_do_basic_steps_on_kbin/jnsozt2/) could have been a reason.

**Comment by JayVii** [comment]
I cannot confirm. searching the above mentioned user works for me on 2.0.0-8
![kbin_follow](https://github.com/toddsundsted/ktistec/assets/28513043/a392bc87-02b7-4acb-84f3-dc18cd58357a)

**Comment by toddsundsted** [comment]
@vrthra i can follow that account, as well. what version are you running?

**Comment by vrthra** [comment]
This is working for me now. I am not sure what changed.
