### ISSUE TITLE
Question: What are the files that Kitstec looks for when it runs?

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#87]
I am trying to find a way to run Ktistec on a somewhat memory constrained Linux system, and I want to get it to serve my current site. The new system does not have the crystal compiler, so I am trying to compile it on another system, and copying it over. Currently, I am trying to compile it with the docker build, and extract the files from the docker image. While doing this, I can get the server to run, but I can't get it to start with my supplied Ktistec database. When I provide the current ktistec.db in the current directory, it asks me to reinitialize the site. Where should I place my current ktistec.db so that it would be recognized? Furthermore, what other files from my previous installation are needed to get Ktistec to run the same site?

**Comment by toddsundsted** [comment]
@vrthra the minimal set of files should be: 1) the executable, 2) everything in `public`, and everything in `etc`.

it should look for ktistec.db in the current directory (the directory from which you run the server). how are you starting the server?

**Comment by vrthra** [comment]
Ah, I see! It works now. I think I was doing something stupid earlier.

**Comment by vrthra** [comment]
While the rest of the application works, I have found that when I try to post with an inline image, the image no longer shows up. Any idea why? Here is a [post](https://gopinath.org/objects/xXp_Rn5QeNE) where I tried adding an image. The image showed when I pasted, but not if I post, and then click edit again.

**Comment by toddsundsted** [comment]
i would assume that the actual upload is failing. the image is displayed in the editor, but not actually uploaded. are there any errors in the browser console and/or the server log? check the permissions on the public/uploads directory and make sure it's writable by whatever user the server is running as.

**Comment by vrthra** [comment]
Thanks, that seems to have been the case. The image was too large. On reducing the size, it went through. Thanks again.
