### ISSUE TITLE
Feature Request: List of "Likes"

### ISSUE THREAD

**Issue by JayVii** [toddsundsted/ktistec#88]
It would be nice to have a list of all posts that I "liked". Sometimes I do use the " like" feature as some sort of bookmark or sometimes I just want to revisit a post that I enjoyed (to see replies, etc).

I suppose the database already lists all posts that I ever "liked" somehow, so it might not be too complicated to list them in an additional menu entry?

**Comment by toddsundsted** [comment]
This is a feature I'd like, as well. Likes are implemented as ActivityPub Like activities and can be found easily with a simple SQL query.

**Comment by toddsundsted** [comment]
I've added this functionality in my working branch. I'm still testing/fixing other changes related to performance. Once that has settled down, I will merge the working branch and announce it here.

**Comment by JayVii** [comment]
Nice! Thank you a lot!

**Comment by toddsundsted** [comment]
this was added in f9eec37c

you can only get to the pages directly—i haven't yet worked it in to the overall navigation.

<your site>/actors/<your name>/likes
<your site>/actors/<your name>/shares

**Comment by JayVii** [comment]
I just upgraded to 2.0.0-10. Thanks a lot, this is exactly what I had in mind!
