### ISSUE TITLE
Question: Mass- and auto-deleting posts

### ISSUE THREAD

**Issue by JayVii** [toddsundsted/ktistec#89]
Is there a way to delete old posts by a SQL-query? Are they gone, when they are deleted from the database or are more steps necessary?

Unfortunately I do not quite get what the [deletion class](https://github.com/toddsundsted/ktistec/blob/acd3ae63737d6bbe1b8eef5fb7b951b85d81ecab/src/models/activity_pub/activity/delete.cr) in ktistec actually does.

**Comment by toddsundsted** [comment]
@JayVii i'd like to consolidate this into https://github.com/toddsundsted/ktistec/issues/77

i think they cover the same concern. generally you could just use SQL to delete a bunch of old posts, and the server should just work correctly (and if it doesn't i'm happy to fix that). however, i think there's a more graceful solution to trimming the database that preserves the things you might want preserved (posts with a hashtag you're particularly interested in, for example).

**Comment by toddsundsted** [comment]
(the Delete class just represents the ActivityPub Delete activity, which transmits actor and object deletions between federated instances. it doesn't do any deleting.)

**Comment by JayVii** [comment]
> @JayVii i'd like to consolidate this into #77

Yes, absolutely! Thanks a lot
