### ISSUE TITLE
Replying to a post on a mastodon instance.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#91]
When I click *reply* from an external mastodon server, I get asked for my home server, like this

<img width="688" alt="image" src="https://github.com/toddsundsted/ktistec/assets/70410/d004d619-3c52-43b7-be48-a3d281f8220d">

and if it is a mastodon server, I get to reply to the post from my server. With the current kitsetec, I get
<img width="402" alt="image" src="https://github.com/toddsundsted/ktistec/assets/70410/a3c6ba46-cdb0-4b85-a784-8185f39e9298">

I understand that I can do the same by searching for the post from my kitstec instance. Is there any way to make this URL compatible for kitstec?

**Comment by toddsundsted** [comment]
it looks like "remote_follow" became "remote_interaction" [here](https://github.com/mastodon/mastodon/pull/8202). that should be relatively easy to support.

**Comment by toddsundsted** [comment]
this is now implemented [here](https://github.com/toddsundsted/ktistec/compare/16e9faf5...d0e00220).
