### ISSUE TITLE
Crash in src20231204140457-migrate-account-state.cr

### ISSUE THREAD

**Issue by EvanKrall** [toddsundsted/ktistec#92]
I was getting this error on startup:

```
Unhandled exception: Missing JSON attribute: last_timeline_checked_at
  parsing Temp_20231204140457::State at line 1, column 1
  deserializing Temp_20231204140457#state (DB::MappingException)
  from ???
  from ???
  from ???
  from ???
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Missing JSON attribute: last_timeline_checked_at
```

My account's `state` column was `{"last_notifications_checked_at":"2024-03-02T01:05:07Z"}`. I was able to work around this by running `update accounts set state = '{"last_notifications_checked_at":"2024-03-02T01:05:07Z", "last_timeline_checked_at":"2024-03-02T01:05:07Z"}' where id = 1;` in the sqlite CLI.

**Comment by toddsundsted** [comment]
@EvanKrall you should be fine. that migration moved these values out of the `state` column and into the `last_times` table. i can definitely make that code more resilient, however.

**Comment by toddsundsted** [comment]
@oztourer moving the discussion over to this issue.

what branch and/or commit are you building off of?

fwiw, you could just delete that migration entirely. it moves timestamps for the last time the notifications and timeline pages were viewed from serialized JSON on the account, to its own table. the code that uses that table will work if the migration doesn't happen.

**Comment by oztourer** [comment]
I am running a Docker build so it takes the current source tree on the -dist branch.

I am not sure what "delete that migration" entails. I did try deleting the last migration record and the 'last_times' table in the hope that it would perform the migration once more but that resulted in recreation of the migration record and table followed by the same error.

As this error first occurred for me days ago and resulted in my instance becoming unavailable I tried building older versions of the code, which mostly failed at the compilation stage (the Dockerfile seems not to have been maintained with regard to using the correct Crystal base image, being stuck on v1.2.2 until switching more recently to 'latest'. I eventually had success with build commit 7a6ef280a from November 2023, with 'crystallang/crystal:1.10-alpine AS builder'. The web page it displays is broken but my build can use the database and communicate with the Fediverse.

I may have done some damage to the integrity of the sqlite database by jumping backwards and forwards in the code history. I am happy to clean up my rather humongous (5GB) database but without guidelines on how to do that I may well do more damage than good.

**Comment by toddsundsted** [comment]
@oztourer i just pushed 520dd8d0 to the [dist](https://github.com/toddsundsted/ktistec/tree/dist) branch.

this fixes the migration by allowing the "last_notifications_checked_at" and "last_timeline_checked_at" properties be missing or `null`.

you should be able to build the docker image from "dist" and deploy as you usually did. let me know if you run into any problems. building and running an older version won't undo any of the migrations—and all of the migration that were applied make changes to the indexes. if you find pages suddenly running super slow, let me know and we can take a look to ensure all of your indexes are in place.

**Comment by oztourer** [comment]
Just to let you know Todd, your fix worked and my instance is back on air (and no slow-downs). Many thanks for the quick response.
